[package]
name = "slippi-re"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.63"
enet = "0.3.0"
json = "0.12.4"
serde = "1.0.144"
serde_derive = "1.0.144"
tokio = { version = "1.21.0", features = [ "full" ] }
warp = "0.3.2"

[[bin]]
name = "slippi-re"
path = "src/main.rs"
